-- MySQL Script generated by MySQL Workbench
-- 03/21/18 08:11:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projektna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektna` DEFAULT CHARACTER SET utf8 ;
USE `projektna` ;

-- -----------------------------------------------------
-- Table `projektna`.`tip_vprasanj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna`.`tip_vprasanj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime_predmeta` VARCHAR(45) NULL,
  `ime_sklopa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna`.`vprasanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna`.`vprasanja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vprasanje` VARCHAR(255) NULL,
  `odgovor` VARCHAR(255) NULL,
  `st_tock` INT NULL,
  `tip_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vprasanja_tip_idx` (`tip_id` ASC),
  CONSTRAINT `fk_vprasanja_tip`
    FOREIGN KEY (`tip_id`)
    REFERENCES `projektna`.`tip_vprasanj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna`.`uporabnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna`.`uporabnik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uporabnisko_ime` VARCHAR(45) NULL,
  `geslo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna`.`evidenca_vprasanj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna`.`evidenca_vprasanj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kolikokrat` INT NULL,
  `uporabnik_id` INT NOT NULL,
  `vprasanja_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evidenca_vprasanj_uporabnik1_idx` (`uporabnik_id` ASC),
  INDEX `fk_evidenca_vprasanj_vprasanja1_idx` (`vprasanja_id` ASC),
  CONSTRAINT `fk_evidenca_vprasanj_uporabnik1`
    FOREIGN KEY (`uporabnik_id`)
    REFERENCES `projektna`.`uporabnik` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evidenca_vprasanj_vprasanja1`
    FOREIGN KEY (`vprasanja_id`)
    REFERENCES `projektna`.`vprasanja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
