-- MySQL Script generated by MySQL Workbench
-- Fri Apr  6 15:44:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projektna2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektna2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektna2` DEFAULT CHARACTER SET utf8 ;
USE `projektna2` ;

-- -----------------------------------------------------
-- Table `projektna2`.`predmeti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`predmeti` (
  `id_predmeta` INT NOT NULL AUTO_INCREMENT,
  `ime_predmeta` VARCHAR(45) NULL,
  PRIMARY KEY (`id_predmeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna2`.`sklopi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`sklopi` (
  `id_sklopa` INT NOT NULL AUTO_INCREMENT,
  `ime_sklopa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sklopa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna2`.`uporabniki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`uporabniki` (
  `id_uporabnika` INT NOT NULL AUTO_INCREMENT,
  `upor_ime` VARCHAR(45) NULL,
  `geslo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_uporabnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna2`.`admini`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`admini` (
  `id_admina` INT NOT NULL AUTO_INCREMENT,
  `id_uporabnika` INT NULL,
  PRIMARY KEY (`id_admina`),
  INDEX `fk_admini_uporabniki_idx` (`id_uporabnika` ASC),
  CONSTRAINT `fk_admini_uporabniki`
    FOREIGN KEY (`id_uporabnika`)
    REFERENCES `projektna2`.`uporabniki` (`id_uporabnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna2`.`vprasanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`vprasanja` (
  `id_vprasanja` INT NOT NULL AUTO_INCREMENT,
  `vprasanje` VARCHAR(45) NULL,
  `odgovor` VARCHAR(45) NULL,
  `st_tock` INT NULL,
  `id_predmeta` INT NOT NULL,
  `id_sklopa` INT NOT NULL,
  PRIMARY KEY (`id_vprasanja`),
  INDEX `fk_vprasanja_predmeti1_idx` (`id_predmeta` ASC),
  INDEX `fk_vprasanja_sklopi1_idx` (`id_sklopa` ASC),
  CONSTRAINT `fk_vprasanja_predmeti1`
    FOREIGN KEY (`id_predmeta`)
    REFERENCES `projektna2`.`predmeti` (`id_predmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vprasanja_sklopi1`
    FOREIGN KEY (`id_sklopa`)
    REFERENCES `projektna2`.`sklopi` (`id_sklopa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projektna2`.`evidenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektna2`.`evidenca` (
  `id_evidence` INT NOT NULL AUTO_INCREMENT,
  `id_uporabnika` INT NOT NULL,
  `id_vprasanja` INT NOT NULL,
  PRIMARY KEY (`id_evidence`),
  INDEX `fk_evidenca_uporabniki1_idx` (`id_uporabnika` ASC),
  INDEX `fk_evidenca_vprasanja1_idx` (`id_vprasanja` ASC),
  CONSTRAINT `fk_evidenca_uporabniki1`
    FOREIGN KEY (`id_uporabnika`)
    REFERENCES `projektna2`.`uporabniki` (`id_uporabnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evidenca_vprasanja1`
    FOREIGN KEY (`id_vprasanja`)
    REFERENCES `projektna2`.`vprasanja` (`id_vprasanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
